export const themeConfigs = {
  gold: {
    headerGradient: "from-[#F3C78B] via-[#F3D9B5] to-[#F3C78B]",
    tagText: "text-yellow-dark",
    descText: "text-yellow-darkest",
    headingText: "text-yellow-dark",
    specialText: "text-yellow-normal-active",
    buttonBg: "bg-yellow-light",
    buttonText: "text-yellow-normal-active",
    timelineBg: "bg-yellow-light",
    timelineText: "text-yellow-darker",
    timelineBorder: "border-yellow-dark",
    boxBg: "bg-[#ffeed1]",
    boxBorder: "border-[#fddeb9]",
    cardBorder: "border-[#fddeb9]",
  },
  green: {
    headerGradient: "from-[#04DF73] via-[#00DA81] to-[#00D591]",
    tagText: "text-[#e6f4ec]",
    descText: "text-[#009245]",
    headingText: "text-[#00833E]",
    buttonBg: "bg-white",
    buttonText: "text-green-normal",
    boxBg: "bg-[#effdf4]",
    boxBorder: "border-green-light",
    timelineBg: "bg-white",
    timelineBorder: "border-green-light",
    timelineText: "text-green-normal",
    specialText: "text-[#009245]",
    cardBorder: "border-green-normal",
  },
  red: {
    headerGradient: "from-[#d22f36] via-[#c9494e] to-[#bb1d23]",
    tagText: "text-[#e6f4ec]",
    descText: "text-[#C1272D]",
    headingText: "text-red-normal-hover",
    specialText: "text-red-normal",
    buttonBg: "bg-red-light",
    buttonText: "text-red-normal-hover",
    timelineBg: "bg-white",
    timelineText: "text-red-normal",
    timelineBorder: "border-red-normal",
    boxBg: "bg-red-normal",
    boxBorder: "border-red-normal",
    boxText: "text-white",
    cardBorder: "border-red-normal",
  },
};
